---
abstract: 'Interface to access AWS CLI configs and credentials'
author:
  - 'IKEDA Kiyoshi <keyamb@cpan.org>'
build_requires:
  File::Temp: '0'
  Test::More: '0.98'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build::Tiny: '0.035'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AWS-CLI-Config
provides:
  AWS::CLI::Config:
    file: lib/AWS/CLI/Config.pm
    version: '0.05'
  AWS::CLI::Config::Profile:
    file: lib/AWS/CLI/Config.pm
    version: '0.05'
requires:
  Carp: '0'
  File::Spec: '0'
  autodie: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/key-amb/perl5-AWS-CLI-Config/issues
  repository: git://github.com/key-amb/perl5-AWS-CLI-Config.git
version: '0.05'
x_contributors:
  - 'Jose Joaquin Atria <jjatria@cpan.org>'
x_serialization_backend: 'YAML::Tiny version 1.70'
